# Generated by Django 2.2.5 on 2020-08-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0002_auto_20200831_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='voice_bridge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
