# Generated by Django 2.2.5 on 2020-09-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0003_auto_20200831_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Indicates whether this meeting is running in BigBlueButton or not!'),
        ),
    ]
