# Generated by Django 2.2.5 on 2020-09-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0004_meeting_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='logout_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='URL to visit after user logged out'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_participants',
            field=models.IntegerField(default=10, verbose_name='Max Participants'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='record',
            field=models.BooleanField(default=True, verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendee_password',
            field=models.CharField(max_length=50, verbose_name='Attendee Password'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='internal_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal Meeting ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Indicates whether this meeting is running in BigBlueButton or not!', verbose_name='Is running'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Meeting ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='moderator_password',
            field=models.CharField(max_length=50, verbose_name='Moderator Password'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of Meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='parent_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Meeting ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='voice_bridge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voice Bridge'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='welcome_text',
            field=models.TextField(default='Welcome!', verbose_name='Meeting Text in Bigbluebutton'),
        ),
    ]
