# Generated by Django 2.2.5 on 2020-09-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0005_auto_20200911_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='allow_start_stop_recording',
            field=models.BooleanField(default=True, help_text='Allow the user to start/stop recording. (default true)', verbose_name='Allow Stop/Start Recording'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='auto_start_recording',
            field=models.BooleanField(default=True, verbose_name='Auto Start Recording'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lock_settings_disable_cam',
            field=models.BooleanField(default=False, help_text='will prevent users from sharing their camera in the meeting', verbose_name='Disable Camera'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lock_settings_disable_mic',
            field=models.BooleanField(default=False, help_text='will only allow user to join listen only', verbose_name='Disable Mic'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lock_settings_disable_note',
            field=models.BooleanField(default=False, help_text='if True will disable notes in the meeting.', verbose_name='Disable Note'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lock_settings_disable_private_chat',
            field=models.BooleanField(default=False, help_text='if True will disable private chats in the meeting', verbose_name='Disable Private chat'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lock_settings_disable_public_chat',
            field=models.BooleanField(default=False, help_text='if True will disable public chat in the meeting', verbose_name='Disable public chat'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lock_settings_locked_layout',
            field=models.BooleanField(default=False, help_text='will lock the layout in the meeting. ', verbose_name='Locked Layout'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='webcam_only_for_moderators',
            field=models.BooleanField(default=False, help_text='will cause all webcams shared by viewers during this meeting to only appear for moderators', verbose_name='Webcam Only for moderators?'),
        ),
    ]
