# Generated by Django 2.2.5 on 2020-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0006_auto_20200911_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='allow_start_stop_recording',
            field=models.BooleanField(default=True, help_text='به کاربر اجازه داده شود تا بتواند ضبط کردن را متوقف یا شروع کن (پیش\u200cفرض بله است)', verbose_name='اجازه دادن برای توقف/اجرای ضبط کردن'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendee_password',
            field=models.CharField(max_length=50, verbose_name='پسورد شرکت کننده'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='auto_start_recording',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی ضبط به صورت اتوماتیک'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='internal_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه ملاقات داخلی (نرم\u200cافزار)'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Indicates whether this meeting is running in BigBlueButton or not!', verbose_name='در حال اجرا'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_cam',
            field=models.BooleanField(default=False, help_text='از اشتراک گذاری دوربین شرکت\u200cکننده\u200cها در جلسه جلوگیری می\u200cکند.', verbose_name='غیرفعال کردن دوربین'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_mic',
            field=models.BooleanField(default=False, help_text='به شرکت\u200cکننده\u200cها فقط اجازه گوش\u200cدادن داده شود.', verbose_name='غیرفعال کردن میکروفون'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_note',
            field=models.BooleanField(default=False, help_text='اگر بله باشد نمی\u200cتوان در جلسه یادداشت اشتراک گذاشت.', verbose_name='غیرفعال کردن یادداشت'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_private_chat',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد چت خصوصی غیرفعال می\u200cشود.', verbose_name='غیرفعال کردن چت خصوصی بین شرکت\u200cکننده\u200cها'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_public_chat',
            field=models.BooleanField(default=False, help_text='اگر بله باشد چت عمومی غیرفعال می\u200cشود.', verbose_name='غیرفعال کردن چت عمومی'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_locked_layout',
            field=models.BooleanField(default=False, help_text='layout در طول ملاقات غیرفعال می\u200cشود.', verbose_name='قفل کردن layout '),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='logout_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='آدرس وب برای هدایت کاربران پس از خروج از ملاقات'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='max_participants',
            field=models.IntegerField(default=10, verbose_name='بیشترین تعداد شرکت\u200cکنندگان'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='شناسه جلسه'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='moderator_password',
            field=models.CharField(max_length=50, verbose_name='پسورد مجری/مدرس'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام ملاقات'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='parent_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه ملاقات والد'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='record',
            field=models.BooleanField(default=True, verbose_name='ضبط کردن'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='voice_bridge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='پل صوتی'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='webcam_only_for_moderators',
            field=models.BooleanField(default=False, help_text='در این حالت دوربین اشتراک گذاشته شده توسط شرکت\u200cکنندگان توسط تنها مجری\u200cها قابل مشاهده باشد.', verbose_name='وب\u200cکم فقط برای مجری و مدرس\u200cها فعال باشد.'),
        ),
    ]
