# Generated by Django 2.2.5 on 2020-10-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0007_auto_20200925_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='allow_start_stop_recording',
            field=models.BooleanField(default=True, help_text='Allow the user to start/stop recording. (default true)', verbose_name='Allow Stop/Start Recording'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendee_password',
            field=models.CharField(max_length=50, verbose_name='Attendee Password'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='auto_start_recording',
            field=models.BooleanField(default=True, verbose_name='Auto Start Recording'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='internal_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal Meeting ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Indicates whether this meeting is running in BigBlueButton or not!', verbose_name='Is running'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_cam',
            field=models.BooleanField(default=False, help_text='will prevent users from sharing their camera in the meeting', verbose_name='Disable Camera'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_mic',
            field=models.BooleanField(default=False, help_text='will only allow user to join listen only', verbose_name='Disable Mic'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_note',
            field=models.BooleanField(default=False, help_text='if True will disable notes in the meeting.', verbose_name='Disable Note'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_private_chat',
            field=models.BooleanField(default=False, help_text='if True will disable private chats in the meeting', verbose_name='Disable Private chat'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_disable_public_chat',
            field=models.BooleanField(default=False, help_text='if True will disable public chat in the meeting', verbose_name='Disable public chat'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lock_settings_locked_layout',
            field=models.BooleanField(default=False, help_text='will lock the layout in the meeting. ', verbose_name='Locked Layout'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='logout_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='URL to visit after user logged out'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='max_participants',
            field=models.IntegerField(default=10, verbose_name='Max Participants'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Meeting ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='moderator_password',
            field=models.CharField(max_length=50, verbose_name='Moderator Password'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of Meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='parent_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Meeting ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='record',
            field=models.BooleanField(default=True, verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='voice_bridge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voice Bridge'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='webcam_only_for_moderators',
            field=models.BooleanField(default=False, help_text='will cause all webcams shared by viewers during this meeting to only appear for moderators', verbose_name='Webcam Only for moderators?'),
        ),
    ]
