# Generated by Django 2.2.5 on 2020-12-10 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_bigbluebutton', '0010_auto_20201126_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='User fullname')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Join Date')),
                ('left_date', models.DateTimeField(blank=True, null=True, verbose_name='Left Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_log', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Meeting Log',
                'verbose_name_plural': 'Meeting Log',
                'db_table': 'meeting_log',
            },
        ),
    ]
