# Generated by Django 2.2.4 on 2020-12-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0011_meetinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinglog',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='django_bigbluebutton.Meeting', verbose_name='Meeting'),
        ),
    ]
