# Generated by Django 2.2.4 on 2020-12-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0013_auto_20201211_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='hook_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Hook ID received from BBB'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='hook_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Hook URL'),
        ),
    ]
