# Generated by Django 2.2.4 on 2021-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bigbluebutton', '0016_auto_20210202_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecord',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Record name'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Meeting Name'),
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='record_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Record ID'),
        ),
    ]
